sed -i 's/import java.io.File/import okio.Path.Companion.toPath\nimport okio.FileSystem/g' shared/src/commonMain/kotlin/com/lucent/app/harness/HarnessPrompt.kt
sed -i 's/val dir = File(HarnessRuntime.filesDirPath(), "harness\/memory")/val dir = HarnessRuntime.filesDirPath().toPath() \/ "harness\/memory"/g' shared/src/commonMain/kotlin/com/lucent/app/harness/HarnessPrompt.kt
sed -i 's/"user" to File(dir, "user.json"),/"user" to dir \/ "user.json",/g' shared/src/commonMain/kotlin/com/lucent/app/harness/HarnessPrompt.kt
sed -i 's/"project" to File(dir, "project-${workspaceSlug()}.json")/"project" to dir \/ "project-${workspaceSlug()}.json"/g' shared/src/commonMain/kotlin/com/lucent/app/harness/HarnessPrompt.kt
sed -i 's/if (!file.isFile) return@forEach/if (FileSystem.SYSTEM.metadataOrNull(file)?.isRegularFile != true) return@forEach/g' shared/src/commonMain/kotlin/com/lucent/app/harness/HarnessPrompt.kt
sed -i 's/private fun factsIn(context: PlatformContext, file: File): List<String> {/private fun factsIn(context: PlatformContext, file: okio.Path): List<String> {/g' shared/src/commonMain/kotlin/com/lucent/app/harness/HarnessPrompt.kt
sed -i 's/File(HarnessRuntime.workspacePath()).name.lowercase().replace(Regex("\[\^a-z0-9\]+"), "-")/HarnessRuntime.workspacePath().toPath().name.lowercase().replace(Regex("\[\^a-z0-9\]+"), "-")/g' shared/src/commonMain/kotlin/com/lucent/app/harness/HarnessPrompt.kt
sed -i 's/val dirs = mutableListOf(File(HarnessRuntime.workspacePath(), ".lucent\/skills"))/val dirs = mutableListOf(HarnessRuntime.workspacePath().toPath() \/ ".lucent\/skills")/g' shared/src/commonMain/kotlin/com/lucent/app/harness/HarnessPrompt.kt
sed -i 's/HarnessRuntime.config().skillDirs.forEach { if (it.isNotBlank()) dirs.add(File(it)) }/HarnessRuntime.config().skillDirs.forEach { if (it.isNotBlank()) dirs.add(it.toPath()) }/g' shared/src/commonMain/kotlin/com/lucent/app/harness/HarnessPrompt.kt
sed -i 's/val files = dirs.filter { it.isDirectory }/val files = dirs.filter { FileSystem.SYSTEM.metadataOrNull(it)?.isDirectory == true }/g' shared/src/commonMain/kotlin/com/lucent/app/harness/HarnessPrompt.kt
sed -i 's/\.flatMap { dir -> (dir.listFiles() ?: emptyArray()).filter { it.isFile && it.name.endsWith(".md") } }/.flatMap { dir -> (try { FileSystem.SYSTEM.list(dir) } catch (e: Exception) { emptyList() }).filter { FileSystem.SYSTEM.metadataOrNull(it)?.isRegularFile == true \&\& it.name.endsWith(".md") } }/g' shared/src/commonMain/kotlin/com/lucent/app/harness/HarnessPrompt.kt
sed -i 's/val label = file.nameWithoutExtension/val label = file.name.substringBeforeLast('\'.'')/g' shared/src/commonMain/kotlin/com/lucent/app/harness/HarnessPrompt.kt
sed -i 's/file.useLines { lines -> lines.firstOrNull { it.startsWith("description:") } }/FileSystem.SYSTEM.read(file) { readUtf8() }.lines().firstOrNull { it.startsWith("description:") }/g' shared/src/commonMain/kotlin/com/lucent/app/harness/HarnessPrompt.kt
