sed -i 's/import java.io.File/import okio.Path\nimport okio.Path.Companion.toPath\nimport okio.FileSystem\nimport okio.buffer/g' shared/src/commonMain/kotlin/com/lucent/app/harness/PlanTools.kt
sed -i 's/private fun fileFor(ctx: HarnessCtx, scope: String): File {/private fun fileFor(ctx: HarnessCtx, scope: String): Path {/g' shared/src/commonMain/kotlin/com/lucent/app/harness/PlanTools.kt
sed -i 's/val dir = HarnessRuntime.subDirPath("memory")/val dir = HarnessRuntime.subDirPath("memory").toPath()/g' shared/src/commonMain/kotlin/com/lucent/app/harness/PlanTools.kt
sed -i 's/"user" -> File(dir, "user.json")/"user" -> dir \/ "user.json"/g' shared/src/commonMain/kotlin/com/lucent/app/harness/PlanTools.kt
sed -i 's/"project" -> File(dir, "project-" + File(HarnessRuntime.workspacePath()).name.lowercase().replace(Regex("\[\^a-z0-9\]+"), "-") + ".json")/"project" -> dir \/ ("project-" + HarnessRuntime.workspacePath().toPath().name.lowercase().replace(Regex("\[\^a-z0-9\]+"), "-") + ".json")/g' shared/src/commonMain/kotlin/com/lucent/app/harness/PlanTools.kt
sed -i 's/else -> File(dir, "session-" + HarnessRuntime.conversationId + ".json")/else -> dir \/ ("session-" + HarnessRuntime.conversationId + ".json")/g' shared/src/commonMain/kotlin/com/lucent/app/harness/PlanTools.kt
sed -i 's/val file = File(HarnessRuntime.workspacePath(), "LUCENT.md")/val file = HarnessRuntime.workspacePath().toPath() \/ "LUCENT.md"/g' shared/src/commonMain/kotlin/com/lucent/app/harness/PlanTools.kt
sed -i 's/if (ctx.config.snapshots && file.exists()) Snapshots.capture(ctx, file)/if (ctx.config.snapshots \&\& FileSystem.SYSTEM.exists(file)) Snapshots.capture(ctx, file.toString())/g' shared/src/commonMain/kotlin/com/lucent/app/harness/PlanTools.kt
sed -i 's/file.appendText((if (file.exists() && file.length() > 0) "\\n" else "") + text + "\\n")/val exists = FileSystem.SYSTEM.exists(file)\n            val len = if (exists) FileSystem.SYSTEM.metadataOrNull(file)?.size ?: -1 else -1\n            val prefix = if (exists \&\& len > 0) "\\n" else ""\n            FileSystem.SYSTEM.appendingSink(file).buffer().use { it.writeUtf8(prefix + text + "\\n") }/g' shared/src/commonMain/kotlin/com/lucent/app/harness/PlanTools.kt
sed -i 's/return ToolExecResult("Appended to ${Workspace.display(ctx, file)}.")/return ToolExecResult("Appended to ${Workspace.display(ctx, file.toString())}.")/g' shared/src/commonMain/kotlin/com/lucent/app/harness/PlanTools.kt
sed -i 's/if (!file.exists()) return ToolExecResult("There are no project notes yet (no LUCENT.md in the workspace).")/if (!FileSystem.SYSTEM.exists(file)) return ToolExecResult("There are no project notes yet (no LUCENT.md in the workspace).")/g' shared/src/commonMain/kotlin/com/lucent/app/harness/PlanTools.kt
sed -i 's/return ToolExecResult(Workspace.readText(file, 64 \* 1024))/return ToolExecResult(Workspace.readText(file.toString(), 64 \* 1024))/g' shared/src/commonMain/kotlin/com/lucent/app/harness/PlanTools.kt
